FROM node:16-alpine as frontend
WORKDIR /app

RUN npm install -g yarn
RUN yarn global add @quasar/cli

COPY frontend/package.json ./
RUN yarn install

COPY frontend/ .
RUN yarn build/web

FROM alpine

RUN apk update && apk add tzdata nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=frontend /app/dist/spa /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
