FROM node:18-alpine as frontend
WORKDIR /app

COPY . /app/

RUN apk add git && \
    yarn global add @quasar/cli

#COPY frontend/package.json ./
#RUN npm install

RUN cd /app/frontend/ && \
    yarn install && \
    yarn build/web/dev


FROM alpine

RUN apk add tzdata nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=frontend /app/frontend/dist/spa /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
