FROM node:18-alpine AS frontend
WORKDIR /app

COPY . .

RUN apk add git && \
    git submodule update --init --remote --merge -- ./frontend/src/shared/lib/flipperzero-protobuf

RUN yarn global add @quasar/cli

RUN cd frontend && \
    yarn install && \
    yarn build/web/dev


FROM flipperdevices/nginx-headers-more-alpine:1.25.1

RUN apk add tzdata

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=frontend /app/frontend/dist/spa /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
